package com.fafmio.avis.initialisation;

import com.fafmio.avis.service.*;
import lombok.AllArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@AllArgsConstructor
@Component
public class AjoutDonneesInitiales implements CommandLineRunner {

    private EditeurService editeurService;
    private ClassificationService classificationService;
    private PlateformeService plateformeService;
    private GenreService genreService;
    private ModeleEconomiqueService modeleEconomiqueService;
    private JeuService jeuService;

//	private static Random random = new Random();

//	private static FakeValuesService fakeValuesService = new FakeValuesService(new Locale("fr-FR"), new RandomService());
//	private static Faker faker = new Faker(new Locale("fr-FR"));

    @Override
    public void run(String... args) throws Exception {

        List<String> list = Arrays.asList(
                "07th Expansion",
                "11 bit studios",
                "1C Company",
                "1492 Studio",
                "2K Games",
                "2K Play",
                "2K Sports",
                "21st Century Entertainment",
                "3D Realms",
                "3DO Company, The",
                "505 Games",
                "5pb.",
                "7th Level",
                "989 Studios",
                "Aackosoft",
                "ABC Software",
                "Absolute Entertainment",
                "Access Software",
                "Acclaim Entertainment",
                "Accolade",
                "Acornsoft",
                "Acquire",
                "Active Gaming Media",
                "Activision",
                "Activision Blizzard",
                "Addictive Games",
                "ADK",
                "Adult Swim Games",
                "Adventure Company, The",
                "Adventure International",
                "Adventure Soft",
                "Aeria Games",
                "Affect",
                "Ageod",
                "Agetec",
                "Akella",
                "Aksys Games",
                "Alawar Entertainment",
                "Alchemist",
                "AliceSoft",
                "AlphaDream",
                "Alphapolis",
                "Alternative Software",
                "Altron",
                "Ambrosia Software",
                "American Game Cartridges",
                "American Laser Games",
                "AMI",
                "Amiga",
                "Amplitude Studios",
                "Amsoft",
                "Anco",
                "Andamiro",
                "Animoca",
                "Ankama Games",
                "Annapurna Interactive",
                "Anuman Interactive",
                "Apogee Software",
                "AQ Interactive",
                "Aquaplus",
                "Arc System Works",
                "ARG Informatique",
                "Arika",
                "Armor Games",
                "Arush Entertainment",
                "ASC Games",
                "Ascaron Entertainment",
                "ASCII",
                "Asmik Ace Entertainment",
                "Aspyr",
                "Asymmetric Publications",
                "Atari",
                "Atari Corporation",
                "Atari Games",
                "Atari Inc.",
                "Atari Inc. (filiale d\'Atari SA)",
                "Atari Interactive",
                "Atari SA",
                "Athena",
                "Atlantis Interactive Entertainment",
                "Atlus",
                "Attic Entertainment Software",
                "Automated Simulations",
                "Avalon Hill",
                "Aztech New Media",
                "Bally Midway Manufacturing Company",
                "Bam! Entertainment",
                "Bandai",
                "Bandai Namco Entertainment",
                "Banpresto",
                "Battlefront.com",
                "BBC Multimedia",
                "Bethesda Softworks",
                "BHV Software",
                "Bigben Interactive",
                "Bigpoint",
                "Bishop",
                "BitRabbit",
                "Black Bean Games",
                "Black Pearl Software",
                "Blackstar Interactive",
                "Bleu-ciel informatique",
                "Blizzard Entertainment",
                "Blue Byte",
                "Blue Mammoth Games",
                "Blue Planet Software",
                "BMG Interactive",
                "Bohemia Interactive",
                "Bonnier Multimedia",
                "Bottom Up",
                "Brøderbund Software",
                "Buena Vista Games",
                "Buka Entertainment",
                "Bulkypix",
                "Bullet-Proof Software",
                "Bungie Studios",
                "Bushiroad",
                "C&E",
                "Camerica",
                "Canal+ Multimedia",
                "Capcom",
                "Capstone Software",
                "Capybara Games",
                "Cave",
                "Cavedog Entertainment",
                "CCP",
                "CD Projekt",
                "cdv Software Entertainment",
                "Cenega",
                "Centuri",
                "Cheetah Mobile",
                "ChessBase",
                "Chucklefish",
                "Chunsoft",
                "CI Games",
                "Cinematronics",
                "Cipher Prime",
                "CipSoft",
                "Cobrasoft",
                "Codemasters",
                "Coffee Stain Studios",
                "Coktel Vision",
                "Coleco",
                "Collavier Corporation",
                "Color Dreams",
                "CommaVid",
                "Commodore",
                "Compile",
                "Conspiracy Entertainment",
                "Core Design",
                "Crave Entertainment",
                "Creative Mobile",
                "CRL Group",
                "Cryo Interactive",
                "Crystal Dynamics",
                "Crytek",
                "Culture Brain",
                "Curve Digital",
                "Cyan Worlds",
                "Cyanide",
                "Cyberdreams",
                "CyberStep",
                "Cygames",
                "D3 Publisher",
                "Daedalic Entertainment",
                "Darewise",
                "Data Becker",
                "Data East",
                "Datamost",
                "Datasoft",
                "Davilex Games",
                "Daybreak Game Company",
                "Dear Villagers",
                "Deep Silver",
                "Dejobaan Games",
                "Delphine Software",
                "Delta Tao Software",
                "Destination Software",
                "Devolver Digital",
                "Digital Integration",
                "Digital Jesters",
                "Digital Pictures",
                "Dinamic Software",
                "Discovery Software",
                "Disney Interactive",
                "Disney Interactive Media Group",
                "Disney Interactive Studios",
                "Disney Mobile Studios",
                "Domark",
                "Dotemu",
                "Double Damage Games",
                "Double Fine Productions",
                "Dovetail Games",
                "DreamCatcher Interactive",
                "DreamWorks Interactive",
                "dtp entertainment",
                "Dynamic Games",
                "Dynamix",
                "EA Chillingo",
                "EA Sports",
                "Edu-Ware",
                "Eidos Interactive",
                "Eighting",
                "Electric Dreams Software",
                "Electronic Arts",
                "Elite Systems",
                "Embracer Group",
                "Emme Interactive",
                "Empire Interactive",
                "En Masse Entertainment",
                "Encore Software",
                "Enix",
                "Enlight Software",
                "Enterbrain",
                "Entertainment Software Publishing",
                "Eon Digital Entertainment",
                "Epic Games",
                "Epic Records Japan",
                "Epoch",
                "Epyx",
                "Ère informatique",
                "ESTsoft",
                "Eugen Systems",
                "Europress",
                "Eversim",
                "Evolved Games",
                "Examu",
                "Exidy",
                "Exkee",
                "Fabtek",
                "Family Soft",
                "Farlan Entertainment",
                "Fatshark",
                "FDG Entertainment",
                "Feral Interactive",
                "Firemonkeys Studios",
                "Fishtank Interactive",
                "Focus Home Interactive",
                "FormGen",
                "Fox Interactive",
                "FoxNext",
                "France Image Logiciel",
                "Froggy Software",
                "FromSoftware",
                "Frontier Developments",
                "FTL Games",
                "Funcom",
                "Funsoft",
                "FuRyu",
                "G2 Games",
                "Gaelco",
                "Game Arts",
                "Game Bakers, The",
                "Game Factory, The",
                "Game&game",
                "Gameforge",
                "Gameloft",
                "Game Studios",
                "GameTek",
                "Garena",
                "Gargoyle Games",
                "Gathering of Developers",
                "Gaumont Multimédia",
                "Gearbox Software",
                "Genki",
                "Ghostlight",
                "Global Star Software",
                "Glu Mobile",
                "Good Shepherd Entertainment",
                "Goodgame Studios",
                "Got Game Entertainment",
                "Gotham Games",
                "GOTO Games",
                "Grandslam Interactive",
                "Great",
                "GREE",
                "Greenwood Entertainment",
                "Gremlin Graphics Software",
                "Gremlin Industries",
                "Grolier Interactive",
                "GT Interactive Software",
                "GT Value Products",
                "GTE Entertainment",
                "GungHo Online Entertainment",
                "Gust",
                "HAL Laboratory",
                "Halfbrick",
                "Hamster",
                "Harebrained Schemes",
                "Hasbro Interactive",
                "Hayden Software",
                "Head Games Publishing",
                "Headup Games",
                "Hello Games",
                "Hewson Consultants",
                "Hi-Rez Studios",
                "Hip Interactive",
                "Hobby Japan",
                "Hudson Soft",
                "Human Entertainment",
                "Humble Bundle",
                "Humongous",
                "Iceberg Interactive",
                "Id Software",
                "Idea Factory",
                "IGS",
                "IJK Software",
                "Image & Form",
                "Image Space Incorporated",
                "Image Works",
                "Imagineer",
                "Imperia Online JSC",
                "Impressions Games",
                "In-Fusio",
                "IncaGold",
                "Index+",
                "Indie Built",
                "indiePub",
                "Infocom",
                "Infogrames Entertainment",
                "Infogrames Interactive",
                "Infogrames North America",
                "Infomedia",
                "Information Global Service",
                "InnoGames",
                "Interactive Magic",
                "Interactive Television Entertainment",
                "Interchannel",
                "Interplay Entertainment",
                "Interstel",
                "Intracorp Entertainment",
                "Introversion Software",
                "Inti Creates",
                "inXile Entertainment",
                "IQ Media",
                "Iridon Interactive",
                "Irem",
                "Jagex",
                "Jaleco",
                "Jorudan",
                "JoWooD Entertainment",
                "Just Flight",
                "Just for Games",
                "Kadokawa Games",
                "Kaga Create",
                "Kairosoft",
                "Kalypso Media",
                "Kaneko",
                "Kemco",
                "Ketchapp",
                "Kiddinx",
                "King",
                "Klei Entertainment",
                "Kobojo",
                "Koei",
                "Koei Tecmo",
                "Konami",
                "Krafton",
                "Krome Studios Melbourne",
                "Lankhor",
                "Larian Studios",
                "Last Day of Work",
                "LCG Entertainment",
                "Learning Company, The",
                "Legacy Interactive",
                "Legend Entertainment Company",
                "Lego Interactive",
                "Leland Corporation",
                "Lemon Interactive",
                "Level-5",
                "Lexis Numérique",
                "Lighthouse Interactive",
                "Linden Lab",
                "LJN",
                "Llamasoft",
                "Loriciel",
                "LucasArts",
                "M. C. Lothlorien",
                "MacPlay",
                "MacSoft Games",
                "Madfinger Games",
                "Magical Company",
                "Majesco Entertainment",
                "Malfador Machinations",
                "MangaGamer",
                "Marvel Games",
                "Marvelous",
                "Marvelous Entertainment",
                "Marvelous USA",
                "Matrix Games",
                "Masaya",
                "Mastertronic",
                "Mattel Electronics",
                "Maxis",
                "MC2 France",
                "Melbourne House",
                "Meridian4",
                "Merscom",
                "Metro3D",
                "MGM Interactive",
                "Mi-Clos Studio",
                "Micro Application",
                "Microfolie\"s",
                "Microids",
                "Micronet co., Ltd.",
                "MicroProse",
                "Microsoft",
                "Midas Interactive Entertainment",
                "Midway Games",
                "Mikengreg",
                "Milestone Interactive",
                "Millennium Interactive",
                "Milton Bradley Company",
                "Mindscape",
                "Mirrorsoft",
                "Mitchell Corporation",
                "Mojang",
                "Molleindustria",
                "Monolith Productions",
                "Monte Cristo Multimedia",
                "Montparnasse Multimedia",
                "Moonstone",
                "MOSS",
                "Motion Twin",
                "MTO",
                "MTV Games",
                "Muse Software",
                "Mystique",
                "Namco",
                "Natsume",
                "Navel",
                "Navigo",
                "NBCUniversal Entertainment Japan",
                "NCS Corporation",
                "NCsoft",
                "Neko Entertainment",
                "NeocoreGames",
                "Neowiz Games",
                "NetEase",
                "New World Computing",
                "Nexon",
                "ngmoco",
                "Niantic",
                "Nicalis",
                "Nightdive Studios",
                "Nihon Bussan",
                "Nihon Falcom",
                "NimbleBit",
                "Nintendo",
                "Nippon Ichi Software",
                "Nitroplus",
                "Nival Interactive",
                "Nova Productions",
                "NovaLogic",
                "Now Production",
                "Nobilis",
                "O3 Entertainment",
                "Oasys Mobile",
                "Ocean Software",
                "Octagon Entertainment",
                "Oculus",
                "Omnitrend Software",
                "On Deck Interactive",
                "On-Line Systems",
                "One Stop Direct",
                "Opal Games",
                "Origin Systems",
                "Outfit7",
                "Oxygen Games",
                "Pack-In-Video",
                "Palace Software",
                "PAN Interactive",
                "Pangea Software",
                "Panasonic Interactive Media",
                "Paradox Interactive",
                "Paramount Digital Entertainment",
                "Penguin Software",
                "Perfect World",
                "Personal Software Services",
                "Petit Ferret",
                "Philips Media",
                "Plarium",
                "Playdigious",
                "Playlogic Entertainment",
                "Playmore",
                "Pokémon Company, The",
                "Pony Canyon",
                "PopCap Games",
                "Portkey Games",
                "Positech Games",
                "Pretty Simple",
                "Private Division",
                "Psikyo",
                "Psygnosis",
                "Psyonix",
                "PUBG Corporation",
                "Purple Moon",
                "Q-Games",
                "Quantic Dream",
                "Quantum Quality Productions",
                "Rage Software",
                "Rare",
                "Rainbow Arts",
                "Rainbow Production",
                "Ravensburger Interactive",
                "RAW Entertainment",
                "Raw Fury",
                "ReadySoft Incorporated",
                "Reality Squared Games",
                "Realtime Associates",
                "Rebellion Developments",
                "Red Barrels",
                "Red Entertainment",
                "Red Orb Entertainment",
                "Red Storm Entertainment",
                "RedOctane",
                "Reef Entertainment",
                "Renegade Software",
                "Renovation Products",
                "Riot Games",
                "Ripcord Games",
                "Rising Star Games",
                "Rockstar Games",
                "Romstar",
                "Rovio Entertainment",
                "Russobit-M",
                "Sammy",
                "Sanritsu Denki",
                "Scavenger",
                "SCi Entertainment",
                "Scimob",
                "Scopely",
                "SdLL",
                "Sega",
                "Sega of America",
                "SegaSoft",
                "Seta",
                "Serenity Forge",
                "Shin'en Multimedia",
                "Shiro Games",
                "Shrapnel Games",
                "Shūeisha",
                "Sierra Entertainment",
                "Simon & Schuster Interactive",
                "SIMS Co.",
                "Simulations Canada",
                "Sir-Tech",
                "Sirius Software",
                "Slash",
                "Small Rockets",
                "Snail",
                "SNK",
                "SNK Playmore",
                "Société occitane d'électronique",
                "Soft Vision",
                "Softdisk",
                "Sony Interactive Entertainment",
                "Sony Online Entertainment",
                "SouthPeak Games",
                "Spectrum HoloByte",
                "Spiderweb Software",
                "Spike",
                "Spike Chunsoft",
                "Square",
                "Square Enix",
                "Stardock",
                "Stern Electronics",
                "Strategic Simulations",
                "Strategic Studies Group",
                "Strategy First",
                "SubLogic",
                "Success",
                "Sulake",
                "Sumo Digital",
                "Sunflowers",
                "Sunsoft",
                "Supercell",
                "Swing! Entertainment",
                "Synapse Software",
                "System 3",
                "T&E Soft",
                "TAD",
                "Taito",
                "Takara Tomy",
                "Take-Two Interactive",
                "Tale of Tales",
                "TalonSoft",
                "Tapulous",
                "Taxan",
                "T-Bull",
                "TDK Mediactive Europe",
                "TDK Mediactive Inc.",
                "Team17",
                "Techland",
                "Technōs Japan",
                "Tecmo",
                "Telecomsoft",
                "Telenet Japan",
                "Telltale Games",
                "Telstar",
                "Tencent Holdings",
                "Tengen",
                "Teque Software",
                "Thalion Software",
                "Thinking Rabbit",
                "THQ",
                "THQ Nordic",
                "Three Melons",
                "Three-Sixty Pacific",
                "Tiertex Design Studios",
                "Time Warner Interactive",
                "tinyBuild Games",
                "Titus Interactive",
                "Toaplan",
                "Toca Boca",
                "Tokuma Shoten",
                "Tomahawk",
                "Tommo",
                "Tonkin House",
                "TopWare Interactive",
                "Towa Chiki",
                "Tradewest",
                "Tradewest Digital",
                "Tradewest Games",
                "Tripwire Interactive",
                "TT Games",
                "U.S. Gold",
                "Ubisoft",
                "UFO Interactive",
                "UK Gold",
                "Ultimate Play the Game",
                "Ultra Software",
                "Uniana",
                "Universal Entertainment",
                "Universal Interactive",
                "UPL",
                "UTV Ignition Games",
                "UTV Indiagames",
                "UTV True Games",
                "ValuSoft",
                "Vatical Entertainment",
                "Valve",
                "Verant Interactive",
                "Versus Evil",
                "Viacom Multimedia",
                "Vic Tokai",
                "Victor Entertainment",
                "Victor Interactive Software",
                "Video System",
                "Virgin Interactive",
                "Virtual Programming",
                "Vivendi Games",
                "VIZ Media",
                "Vlambeer",
                "Voodoo",
                "Wadjet Eye Games",
                "Wanadoo Edition",
                "Wargaming.net",
                "Warner Bros. Interactive Entertainment",
                "Warner Interactive Entertainment",
                "WayForward Technologies",
                "Webzen",
                "Wemade Entertainment",
                "WildTangent",
                "Williams Electronics Games",
                "Windmill Software",
                "Winkysoft",
                "Wisdom Tree",
                "WizardWorks Group, The",
                "WizardWorks Software",
                "Wolf Team",
                "Working Designs",
                "WMS Industries",
                "Xicat Interactive",
                "Xbox Game Studios",
                "XS Games",
                "XSEED Games",
                "Yamasa",
                "Yanoman",
                "Yuke\"s",
                "Yutaka",
                "Zachtronics",
                "Zallag",
                "Zen Studios",
                "ZeniMax Media",
                "Zimag",
                "Zoo",
                "Zoo Digital Publishing",
                "Zoo Games",
                "Zushi Games",
                "Zuxxez Entertainment",
                "Zynga"
        );

        for (String ed : list) {
            editeurService.ajouterEditeur(ed);
        }


        plateformeService.ajouterPlateforme("PC");
        plateformeService.ajouterPlateforme("Game Cube");
        plateformeService.ajouterPlateforme("Nintendo DS");
        plateformeService.ajouterPlateforme("Switch");
        plateformeService.ajouterPlateforme("Wii");
        plateformeService.ajouterPlateforme("Wii U");
        plateformeService.ajouterPlateforme("Playstation 1");
        plateformeService.ajouterPlateforme("Playstation 2");
        plateformeService.ajouterPlateforme("Playstation 3");
        plateformeService.ajouterPlateforme("Playstation 4");
        plateformeService.ajouterPlateforme("Playstation 5");
        plateformeService.ajouterPlateforme("Xbox 360");
        plateformeService.ajouterPlateforme("Xbox One");
        plateformeService.ajouterPlateforme("Xbox Series");

        classificationService.ajouterClassification("PEGI 3");
        classificationService.ajouterClassification("PEGI 7");
        classificationService.ajouterClassification("PEGI 12");
        classificationService.ajouterClassification("PEGI 16");
        classificationService.ajouterClassification("PEGI 18");

        genreService.ajouterGenre("FPS (First Person Shooter)");
        genreService.ajouterGenre("RTS (Real-Time Strategy)");
        genreService.ajouterGenre("RPG (Role-Playing Game)");
        genreService.ajouterGenre("Simulation");
        genreService.ajouterGenre("Gestion");
        genreService.ajouterGenre("TPS (Third Person Shooter)");
        genreService.ajouterGenre("Digital Collectible Card Game");
        genreService.ajouterGenre("MOBA (Multiplayer Online Battle Arena)");
        genreService.ajouterGenre("MMORPG (Massively Multiplayer Online Role-Playing Game)");

        modeleEconomiqueService.ajouterModeleEconomique("Premium");
        modeleEconomiqueService.ajouterModeleEconomique("Abonnement");
        modeleEconomiqueService.ajouterModeleEconomique("Free To Play");
        modeleEconomiqueService.ajouterModeleEconomique("Freemium / Free To Start");
        modeleEconomiqueService.ajouterModeleEconomique("Accès Anticipé / Early Access");
        modeleEconomiqueService.ajouterModeleEconomique("Financement Participatif");
        modeleEconomiqueService.ajouterModeleEconomique("Play 2 Earn");
        modeleEconomiqueService.ajouterModeleEconomique("Pay What You Want");
    }
}
